version: '3'

services:
  metadata-server:
    build:
      context: ./metadata-server
      dockerfile: Dockerfile
    volumes:
      - ./metadata-server:/app
      - ./consts.json:/app/consts.json
    networks:
      server-network:
        ipv4_address: "11.56.1.21"
    hostname: "metadata-server"
  
  storage-node-1:
    build:
      context: ./storage-node
      dockerfile: Dockerfile
    depends_on:
      - metadata-server
    volumes:
      - ./storage-node:/app
      - ./consts.json:/app/consts.json
    networks:
      server-network:
        ipv4_address: "11.56.1.41"
    hostname: "storage-node-1"

  storage-node-2:
    build:
      context: ./storage-node
      dockerfile: Dockerfile
    depends_on:
      - metadata-server
    volumes:
      - ./storage-node:/app
      - ./consts.json:/app/consts.json
    networks:
      server-network:
        ipv4_address: "11.56.1.42"
    hostname: "storage-node-2"
  
  storage-node-3:
    build:
      context: ./storage-node
      dockerfile: Dockerfile
    depends_on:
      - metadata-server
    volumes:
      - ./storage-node:/app
      - ./consts.json:/app/consts.json
    networks:
      server-network:
        ipv4_address: "11.56.1.43"
    hostname: "storage-node-3"

networks:
  server-network:
    ipam:
      driver: default
      config:
        - subnet: "11.56.1.0/24"